# Generated by Django 3.1.5 on 2021-01-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_userrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_number',
            new_name='mobile',
        ),
    ]
