# Generated by Django 3.1.5 on 2021-01-27 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_userrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('company',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.company')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                      related_name='employee',
                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
