# Generated by Django 3.1.5 on 2021-01-25 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20210125_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=12,
                                   validators=[django.core.validators.RegexValidator(regex='\\+[0-9]{11}')]),
        ),
    ]
