# Generated by Django 3.1.5 on 2021-02-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageNiveau',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
