# Generated by Django 3.1.5 on 2021-02-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20210203_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='languageniveau',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
    ]
