# Generated by Django 3.1.5 on 2021-02-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20210203_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageNiveau',
            new_name='LanguageLevel',
        ),
    ]
