# Generated by Django 3.1.5 on 2021-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_auto_20210203_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
            ],
        ),
    ]
