# Generated by Django 3.1.5 on 2021-02-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_onlineproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDistinctions',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
