# Generated by Django 3.1.5 on 2021-02-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_mydistinctions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyDistinctions',
            new_name='Distinction',
        ),
    ]
