# Generated by Django 3.1.5 on 2021-02-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_auto_20210203_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinction',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='onlineproject',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
