# Generated by Django 3.1.5 on 2021-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_auto_20210203_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('anonymous', 'Anonymous'), ('public', 'Public')], default='incomplete', max_length=255),
        ),
    ]
