# Generated by Django 3.1.5 on 2021-02-04 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_auto_20210204_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.student'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='db.student'),
        ),
        migrations.AlterField(
            model_name='onlineproject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.student'),
        ),
        migrations.AlterField(
            model_name='userlanguagerelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.student'),
        ),
    ]
