# Generated by Django 3.1.5 on 2021-02-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_student_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
