# Generated by Django 3.1.5 on 2021-02-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0023_auto_20210209_1714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userlanguagerelation',
            unique_together={('language', 'student')},
        ),
    ]
