# Generated by Django 3.1.5 on 2021-02-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0024_joboption'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name', ),
            },
        ),
        migrations.AlterModelOptions(
            name='joboption',
            options={'ordering': ('name', )},
        ),
    ]
