# Generated by Django 3.1.5 on 2021-02-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0026_auto_20210208_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboption',
            old_name='type',
            new_name='mode',
        ),
    ]
