# Generated by Django 3.1.5 on 2021-02-04 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0027_auto_20210210_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='distinction',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hobby',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineproject',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='db.Skill'),
        ),
        migrations.CreateModel(
            name='UserLanguageRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.language')),
                ('language_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.languagelevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('language', 'language_level')},
            },
        ),
    ]
