# Generated by Django 3.1.5 on 2021-02-04 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0028_auto_20210204_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='hobbies',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
