# Generated by Django 3.1.5 on 2021-02-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0031_auto_20210209_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distinction',
            unique_together={('text', 'student')},
        ),
    ]
