# Generated by Django 3.1.5 on 2021-02-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0033_auto_20210210_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagelevel',
            options={'ordering': ['level']},
        ),
        migrations.RenameField(
            model_name='languagelevel',
            old_name='name',
            new_name='level',
        ),
    ]
