# Generated by Django 3.1.5 on 2021-02-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0034_auto_20210215_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagelevel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
