# Generated by Django 3.1.5 on 2021-02-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0035_languagelevel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguagerelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='languages',
                                    to='db.student'),
        ),
    ]
