# Generated by Django 3.1.5 on 2021-02-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0036_auto_20210215_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='distinctions',
                                    to='db.student'),
        ),
        migrations.AlterField(
            model_name='onlineproject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='online_projects',
                                    to='db.student'),
        ),
    ]
