# Generated by Django 3.1.5 on 2021-02-18 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_auto_20210216_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='\\+[0-9]{11}')]),
        ),
    ]
