# Generated by Django 3.1.5 on 2021-02-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0037_auto_20210216_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='job_option',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='db.joboption'),
        ),
        migrations.AlterField(
            model_name='student',
            name='job_position',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='db.jobposition'),
        ),
    ]
