# Generated by Django 3.1.5 on 2021-02-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_delete_distinction'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='distinction',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
