# Generated by Django 3.1.5 on 2021-02-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_auto_20210217_1033'),
    ]

    operations = [
        migrations.DeleteModel(name='Distinction', ),
    ]
