# Generated by Django 3.1.5 on 2021-02-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_auto_20210218_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='member_it_st_gallen',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='company',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.branch'),
        ),
    ]
