# Generated by Django 3.1.5 on 2021-02-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('db', '0038_customrendition_file_image_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('attachment_id', models.PositiveIntegerField()),
                ('attachment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachement_type', to='contenttypes.contenttype')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_type', to='contenttypes.contenttype')),
            ],
        ),
    ]
