# Generated by Django 3.1.5 on 2021-02-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0038_attachment_customrendition_file_image_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
