# Generated by Django 3.1.5 on 2021-02-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_auto_20210222_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='position',
        ),
    ]
