# Generated by Django 3.1.5 on 2021-02-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0039_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='key',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
