# Generated by Django 3.1.5 on 2021-02-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('db', '0040_attachment_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_type', to='contenttypes.contenttype'),
        ),
    ]
