# Generated by Django 3.1.5 on 2021-02-25 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0040_remove_company_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['icon'],
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='\\+[0-9]{11}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='uid',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='CHE-[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='\\+[0-9]{11}$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='benefits',
            field=models.ManyToManyField(related_name='benefits', to='db.Benefit'),
        ),
    ]
