# Generated by Django 3.1.5 on 2021-02-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0041_auto_20210225_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_positions',
            field=models.ManyToManyField(related_name='job_positions', to='db.JobPosition'),
        ),
    ]
