# Generated by Django 3.1.5 on 2021-03-02 12:18
from django.db import migrations, models

import db.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_auto_20210224_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=db.models.file.get_upload_to, verbose_name='file'),
        ),
    ]
