# Generated by Django 3.1.5 on 2021-03-02 11:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_auto_20210224_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['icon'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='job_positions',
            field=models.ManyToManyField(related_name='job_positions', to='db.JobPosition'),
        ),
        migrations.AddField(
            model_name='company',
            name='member_it_st_gallen',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='\\+[0-9]{11}$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='company',
            name='uid',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='CHE-[0-9]{3}\\.[0-9]{3}\\.[0-9]{3}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='\\+[0-9]{11}$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='benefits',
            field=models.ManyToManyField(related_name='benefits', to='db.Benefit'),
        ),
        migrations.AddField(
            model_name='company',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.branch'),
        ),
    ]
