# Generated by Django 3.1.5 on 2021-02-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_company_job_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
