# Generated by Django 3.1.5 on 2021-03-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0043_auto_20210302_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ('icon',)},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ('name',)},
        ),
    ]
