# Generated by Django 3.1.5 on 2021-03-10 17:03

from django.db import migrations
from django.utils.text import slugify


def populate_reference(apps, schema_editor):
    company = apps.get_model('db', 'Company')
    for obj in company.objects.all():
        obj.slug = slugify(obj.name)
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0045_company_slug'),
    ]

    operations = [
        migrations.RunPython(populate_reference),
    ]
