# Generated by Django 3.1.5 on 2021-03-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0047_auto_20210308_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(to='db.Skill'),
        ),
    ]
