# Generated by Django 3.1.5 on 2021-03-10 17:03

from django.db import migrations, connection
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    cursor = connection.cursor()
    company = apps.get_model('db', 'Company')
    for obj in company.objects.raw('SELECT * FROM db_company'):
        query = f"UPDATE db_company SET slug={slugify(obj.name)} WHERE id={obj.id}"
        cursor.execute(query)


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0047_company_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
