# Generated by Django 3.1.5 on 2021-03-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0053_jobposting_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingLanguageRelation',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('job_posting',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='languages',
                                   to='db.jobposting')),
                ('language',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.language')),
                ('language_level',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='db.languagelevel')),
            ],
            options={
                'unique_together': {('language', 'job_posting')},
            },
        ),
    ]
