# Generated by Django 3.1.5 on 2021-03-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0055_language_short_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='db.joboption'),
        ),
    ]
