# Generated by Django 3.1.5 on 2021-03-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0055_language_short_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='workload',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
