# Generated by Django 3.1.5 on 2021-03-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_auto_20210310_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public')],
                                   default='draft',
                                   max_length=255),
        ),
    ]
