# Generated by Django 3.1.5 on 2021-03-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0056_softskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='soft_skill',
            field=models.ManyToManyField(blank=True, related_name='soft_skills', to='db.SoftSkill'),
        ),
    ]
