# Generated by Django 3.1.5 on 2021-03-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0061_auto_20210317_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(choices=[('incomplete', 'Incomplete'),
                                            ('anonymous', 'Anonymous'), ('public', 'Public')],
                                   default='incomplete',
                                   max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('incomplete', 'Incomplete'),
                                            ('anonymous', 'Anonymous'), ('public', 'Public')],
                                   default='incomplete',
                                   max_length=255),
        ),
    ]
