# Generated by Django 3.1.5 on 2021-03-22 13:59
from django.db import connection
from django.db import migrations
from django.contrib.auth import get_user_model

from db.models import ProfileType, Student


def move_profile_state(apps, schema_editor):
    cursor = connection.cursor()
    users = get_user_model().objects.raw('SELECT * FROM db_user;')

    for user in users:
        state = user.__dict__.get('state')
        step = user.__dict__.get('profile_step')
        if getattr(user, 'type') in ProfileType.valid_company_types():
            company_id = user.__dict__.get('company_id')
            query = f"UPDATE db_company SET state={state}, profile_step={str(step)} WHERE id={str(company_id)};"
            cursor.execute(query)
        elif getattr(user, 'type') in ProfileType.valid_student_types():
            query = f"SELECT * FROM db_student WHERE user_id={getattr(user, 'id')};"
            student = Student.objects.raw(query)
            query = f"UPDATE db_student SET state={state}, profile_step={str(step)} WHERE id={str(student[0].id)};"
            cursor.execute(query)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0062_auto_20210322_1409'),
    ]

    operations = [
        migrations.RunPython(move_profile_state, migrations.RunPython.noop),
    ]
