# Generated by Django 3.1.5 on 2021-03-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0063_auto_20210322_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_step',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
