# Generated by Django 3.1.5 on 2021-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0064_auto_20210322_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='top_level_organisation_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='top_level_organisation_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
