# Generated by Django 3.1.5 on 2021-03-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0065_auto_20210323_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(blank=True,
                                   choices=[('internal', 'Internal'), ('student', 'Student'),
                                            ('college-student', 'College Student'),
                                            ('junior', 'Junior'), ('company', 'Company'),
                                            ('university', 'University'), ('other', 'Other')],
                                   max_length=255),
        ),
    ]
