# Generated by Django 3.1.5 on 2021-03-23 10:32
from django.contrib.auth import get_user_model
from django.db import migrations

from db.models import UserType


def copy_user_type(apps, schema_editor):
    users = get_user_model().objects.all()

    for user in users:
        if user.type in UserType.valid_company_types():
            user.company.type = user.type
            user.company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0066_company_type'),
    ]

    operations = [
        migrations.RunPython(copy_user_type, migrations.RunPython.noop),
    ]
