# Generated by Django 3.1.5 on 2021-03-23 10:32
from django.contrib.auth import get_user_model
from django.db import migrations
from django.db import connection

from db.models import ProfileType


def copy_user_type(apps, schema_editor):
    cursor = connection.cursor()
    users = get_user_model().objects.raw('SELECT * FROM db_user;')

    for user in users:
        if getattr(user, 'type') in ProfileType.valid_company_types():
            company_id = getattr(user, 'company_id')
            user_type = getattr(user, 'type')
            query = f"UPDATE db_company SET type={user_type} WHERE id={str(company_id)};"
            cursor.execute(query)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0066_company_type'),
    ]

    operations = [
        migrations.RunPython(copy_user_type, migrations.RunPython.noop),
    ]
