# Generated by Django 3.1.5 on 2021-03-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0067_auto_20210323_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='top_level_organisation_url',
            new_name='top_level_organisation_website',
        ),
    ]
