# Generated by Django 3.1.5 on 2021-03-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0068_auto_20210323_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='link_education',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='link_projects',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='link_thesis',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
