# Generated by Django 3.1.5 on 2021-03-24 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0069_auto_20210323_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='workload',
            field=models.IntegerField(blank=True,
                                      default=100,
                                      null=True,
                                      validators=[
                                          django.core.validators.MaxValueValidator(100),
                                          django.core.validators.MinValueValidator(10)
                                      ]),
        ),
    ]
