# Generated by Django 3.1.5 on 2021-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0071_auto_20210324_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='soft_skills',
            field=models.ManyToManyField(blank=True, related_name='students', to='db.SoftSkill'),
        ),
    ]
