# Generated by Django 3.1.5 on 2021-03-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0073_auto_20210330_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='expectations',
            new_name='job_requirements',
        ),
    ]
