# Generated by Django 3.1.5 on 2021-03-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0074_auto_20210330_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOption',
            new_name='JobType',
        ),
    ]
