# Generated by Django 3.1.5 on 2021-03-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0075_auto_20210330_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='job_option',
            new_name='job_type',
        ),
    ]
