# Generated by Django 3.1.5 on 2021-03-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0076_auto_20210330_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='job_option',
            new_name='job_type',
        ),
    ]
