# Generated by Django 3.1.5 on 2021-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0077_auto_20210330_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalFit',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('student', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
    ]
