# Generated by Django 3.1.5 on 2021-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0079_student_cultural_fits'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cultural_fits',
            field=models.ManyToManyField(related_name='companies', to='db.CulturalFit'),
        ),
    ]
