# Generated by Django 3.1.5 on 2021-04-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0080_company_cultural_fits'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='db.faqcategory')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='faqs',
            field=models.ManyToManyField(related_name='companies', to='db.FAQ'),
        ),
    ]
