# Generated by Django 3.1.5 on 2021-04-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0082_auto_20210406_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='branch',
        ),
    ]
