# Generated by Django 3.1.5 on 2021-04-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0083_remove_company_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job_positions',
        ),
    ]
