# Generated by Django 3.1.5 on 2021-04-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0084_remove_company_job_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='job_position',
        ),
    ]
