# Generated by Django 3.1.5 on 2021-04-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0089_auto_20210410_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
