# Generated by Django 3.1.5 on 2021-04-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0091_auto_20210410_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
