# Generated by Django 3.1.5 on 2021-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0093_auto_20210410_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagelevel',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
