# Generated by Django 3.1.5 on 2021-04-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0094_languagelevel_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_confirmed', models.BooleanField(default=False)),
                ('company_confirmed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_confirmed', models.DateTimeField(null=True)),
                ('initiator', models.CharField(choices=[('student', 'Student'), ('company', 'Company')], max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.student')),
            ],
        ),
    ]
