# Generated by Django 3.1.5 on 2021-04-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0095_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='title',
        ),
    ]
