# Generated by Django 3.1.5 on 2021-04-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0095_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='job_posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.jobposting'),
        ),
    ]
