# Generated by Django 3.1.5 on 2021-04-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0095_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='complete_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
