# Generated by Django 3.1.5 on 2021-04-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0096_match_complete_mail_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='complete',
        ),
    ]
