# Generated by Django 3.1.5 on 2021-04-21 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0096_match_complete_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposting',
            name='date_published',
            field=models.DateTimeField(null=True),
        ),
    ]
