# Generated by Django 3.1.5 on 2021-05-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0099_auto_20210421_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='key',
            field=models.CharField(choices=[('student_avatar', 'Student Avatar'),
                                            ('student_documents', 'Student Documents'),
                                            ('company_avatar', 'Company Avatar'),
                                            ('company_documents', 'Company Documents'),
                                            ('student_avatar_fallback', 'Student Avatar fallback'),
                                            ('company_avatar_fallback', 'Company Avatar fallback')],
                                   max_length=100),
        ),
    ]
