# Generated by Django 3.1.5 on 2021-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0100_auto_20210510_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='branches',
            field=models.ManyToManyField(related_name='job_postings', to='db.Branch'),
        ),
    ]
