# Generated by Django 3.1.5 on 2021-05-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0102_auto_20210517_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='branch',
        ),
    ]
