# Generated by Django 3.1.5 on 2021-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0103_remove_jobposting_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='services',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
