# Generated by Django 3.1.5 on 2022-01-29 23:48

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.AlterField(
            model_name='Attachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Benefit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='CulturalFit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='FAQCategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='File',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Hobby',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='JobPostingLanguageRelation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='JobPosting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='JobRequirement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='JobType',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Keyword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='LanguageLevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Language',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Match',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='OnlineProject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='ProjectPosting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='ProjectType',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Skill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='SoftSkill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Topic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='UserLanguageRelation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='UserRequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='User',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
        migrations.AlterField(
            model_name='Video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True),
        ),
    ]