# Generated by Django 3.2.14 on 2022-07-06 10:56

from django.db import migrations, models
from django.db import connection


def combine_topic_with_keywords(apps, schema_editor):
    Topic = apps.get_model('db', 'Topic')
    Keyword = apps.get_model('db', 'Keyword')

    for topic in Topic.objects.all():
        Keyword.objects.get_or_create(name=topic.name)


def update_project_posting_keywords(apps, schema_editor):
    cursor = connection.cursor()
    ProjectPosting = apps.get_model('db', 'ProjectPosting')
    Keyword = apps.get_model('db', 'Keyword')

    for project_posting in ProjectPosting.objects.all():
        keyword = Keyword.objects.get(name=project_posting.topic.name)

        query = "INSERT INTO `db_projectposting_keywords` (`projectposting_id`, `keyword_id`) VALUES (%i, %i);" % \
                (project_posting.id, keyword.id)
        cursor.execute(query)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0109_student_is_matchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RunPython(combine_topic_with_keywords),
        migrations.RunPython(update_project_posting_keywords),
        migrations.RemoveField(
            model_name='projectposting',
            name='topic',
        ),
        migrations.DeleteModel(name='Topic', ),
    ]
