# Generated by Django 3.2.14 on 2022-07-06 10:56

from django.db import migrations, models
from django.db import connection


def combine_topic_with_keywords(apps, schema_editor):
    cursor = connection.cursor()

    query = "INSERT INTO db_keyword (name) \
                SELECT \
                    name \
                    FROM db_topic \
                    WHERE db_topic.name NOT IN (SELECT name FROM db_keyword);"

    cursor.execute(query)


def update_project_posting_keywords(apps, schema_editor):
    cursor = connection.cursor()
    
    query = "INSERT INTO \
        db_projectposting_keywords \
        (projectposting_id, keyword_id) \
        SELECT \
            db_projectposting.id, \
            db_keyword.id \
            FROM db_projectposting \
            JOIN db_topic on db_projectposting.topic_id = db_topic.id \
            JOIN db_keyword ON db_keyword.name = db_topic.name \
            WHERE db_keyword.id NOT IN ( \
                SELECT id \
                FROM db_projectposting_keywords \
                WHERE db_projectposting_keywords.projectposting_id = db_projectposting.id);"

    cursor.execute(query)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0109_student_is_matchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RunPython(combine_topic_with_keywords),
        migrations.RunPython(update_project_posting_keywords),
        migrations.RemoveField(
            model_name='projectposting',
            name='topic',
        ),
        migrations.DeleteModel(name='Topic', ),
    ]
