# Generated by Django 3.2.14 on 2022-07-06 13:44

from django.db import migrations, models


def combine_description_with_additional_information(apps, schema_editor):
    ProjectPosting = apps.get_model('db', 'ProjectPosting')

    for project_posting in ProjectPosting.objects.all():
        project_posting.description = project_posting.description + "\n" + project_posting.additional_information
        project_posting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0110_combine_topics_with_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectposting',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.RunPython(combine_description_with_additional_information),
        migrations.RemoveField(
            model_name='projectposting',
            name='additional_information',
        ),
    ]
