# Generated by Django 3.2.14 on 2022-07-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0111_merge_descriptions_for_project_postings'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectposting',
            name='compensation',
            field=models.TextField(default='-', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectposting',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
