# Generated by Django 3.2.14 on 2022-07-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0111_merge_descriptions_for_project_postings'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectposting',
            name='compensation',
            field=models.TextField(max_length=300, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectposting',
            name='team_size',
            field=models.IntegerField(null=True, default=None),
        ),
    ]
