# Generated by Django 4.1.7 on 2023-04-05 14:44

from django.db import migrations, models
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('db', '0113_rename_project_to_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='compensation',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='company',
            name='top_level_organisation_description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='customrendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(
                height_field='height',
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field='width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=wagtail.images.models.WagtailImageField(
                height_field='height',
                upload_to=wagtail.images.models.get_upload_to,
                verbose_name='file',
                width_field='width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='student',
            name='distinction',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text=
                'The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                related_name='user_set',
                related_query_name='user',
                to='auth.group',
                verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text=
                'Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                verbose_name='active'),
        ),
    ]
