# Generated by Django 4.1.9 on 2023-06-01 13:59

import django.core.validators
from django.db import migrations, models


def fill_workload_from_and_workload_to(apps, schema_editor):
    JobPosting = apps.get_model('db', 'JobPosting')

    for job_posting in JobPosting.objects.all():
        job_posting.workload_from = job_posting.workload
        job_posting.workload_to = job_posting.workload
        job_posting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0114_alter_challenge_compensation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='workload_from',
            field=models.IntegerField(validators=[
                django.core.validators.MaxValueValidator(100),
                django.core.validators.MinValueValidator(10)
            ]),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='workload_to',
            field=models.IntegerField(validators=[
                django.core.validators.MaxValueValidator(100),
                django.core.validators.MinValueValidator(10)
            ]),
        ),
        migrations.RunPython(fill_workload_from_and_workload_to),
        migrations.RemoveField(
            model_name='jobposting',
            name='workload',
        ),
    ]
