# Generated by Django 4.1.9 on 2023-06-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0115_remove_jobposting_workload_jobposting_workload_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_period_by_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_from_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
