# Generated by Django 4.1.9 on 2023-06-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0115_remove_jobposting_workload_jobposting_workload_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_from_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
