# Generated by Django 4.1.10 on 2023-07-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0116_alter_jobposting_date_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_step',
        ),
        migrations.AlterField(
            model_name='student',
            name='cultural_fits',
            field=models.ManyToManyField(blank=True,
                                         null=True,
                                         related_name='students',
                                         to='db.culturalfit'),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', to='db.skill'),
        ),
        migrations.AlterField(
            model_name='student',
            name='soft_skills',
            field=models.ManyToManyField(blank=True,
                                         null=True,
                                         related_name='students',
                                         to='db.softskill'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('incomplete', 'Incomplete'),
                                            ('anonymous', 'Anonymous'), ('public', 'Public')],
                                   default='public',
                                   max_length=255),
        ),
    ]
