# Generated by Django 4.1.10 on 2023-08-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0117_remove_student_profile_step_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='profile_step',
        ),
        migrations.AlterField(
            model_name='company',
            name='benefits',
            field=models.ManyToManyField(null=True, related_name='companies', to='db.benefit'),
        ),
        migrations.AlterField(
            model_name='company',
            name='branches',
            field=models.ManyToManyField(null=True, related_name='companies', to='db.branch'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='cultural_fits',
            field=models.ManyToManyField(null=True, related_name='companies', to='db.culturalfit'),
        ),
        migrations.AlterField(
            model_name='company',
            name='soft_skills',
            field=models.ManyToManyField(null=True, related_name='companies', to='db.softskill'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(choices=[('anonymous', 'Anonymous'), ('public', 'Public')],
                                   default='public',
                                   max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('anonymous', 'Anonymous'), ('public', 'Public')],
                                   default='public',
                                   max_length=255),
        ),
    ]
