# Generated by Django 6.0 on 2025-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0120_alter_customrendition_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media items'
            },
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True,
                                   default='',
                                   max_length=255,
                                   verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
    ]
