# Generated by Django 6.0 on 2025-12-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_video_options_image_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_requirements',
            field=models.ManyToManyField(to='db.jobrequirement'),
        ),
    ]
