stages:
  - "Test"
  - "Build"

pylint:
  image:
    docker.gitlab.liip.ch/matchd/docker-images/python-38-centos7:latest
  script:
    - pip install --upgrade pip && pip install -r requirements.txt
    - pylint --load-plugins pylint_django --django-settings-module=app.settings.test api app db
  stage: "Test"
  only:
    - branches
    - tags
  tags:
    - docker
    - swiss
    - not-roadrunner

test:
  image:
    docker.gitlab.liip.ch/matchd/docker-images/python-38-centos7:latest
  script:
    - pip install --upgrade pip && pip install -r requirements.txt
    - until curl -s http://elasticsearch:9200/_cluster/health | egrep '(green|yellow)' -i > /dev/null; do echo "elastic is not ready. waiting..." && sleep 5; done
    - ./manage.py test --settings app.settings.test
  stage: "Test"
  only:
    - branches
    - tags
  tags:
    - docker
    - swiss
    - not-roadrunner
  services:
    - name: mariadb:10.3.22
      alias: api-db
    - name: docker.gitlab.liip.ch/matchd/docker-images/elastic-search:latest
      alias: elasticsearch
      command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]
  variables:
    MYSQL_DATABASE: "wagtail"
    MYSQL_USER: "wagtail"
    MYSQL_PASSWORD: "wagtail"
    MYSQL_ROOT_PASSWORD: "wagtail"
    DJANGO_DB_HOST: 'api-db'
    DJANGO_DB_PORT: '3306'
    DJANGO_DB_NAME: 'wagtail'
    DJANGO_DB_USER: 'root'
    DJANGO_DB_PW: 'wagtail'
    DJANGO_ELASTIC_SEARCH_URL: 'http://elasticsearch:9200'
  interruptible: true

.build: &build
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - >
    docker build
    -t "$CI_REGISTRY/matchd/backend:$APP_TAG"
    -f "docker/Dockerfile" .
  - docker push $CI_REGISTRY/matchd/backend:$APP_TAG

build:development:
  image: docker:19.03.11
  stage: "Build"
  services:
    - docker:19.03.11-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    APP_TAG: $CI_COMMIT_SHA
  script:
    - *build
  dependencies:
    - test
  only:
    - MATCHD-46-deployment
  tags:
    - docker
    - docker-nonswiss-ok
    - not-roadrunner
  interruptible: true
  resource_group: development

build:integration:
  image: docker:19.03.11
  stage: "Build"
  services:
    - docker:19.03.11-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    APP_TAG: $CI_COMMIT_REF_NAME
  script:
    - *build
  dependencies:
    - test
  only:
    refs:
      - /^v?\d+\.\d+\.\d+(?:-(?:alpha|beta|rc)(?:(?:(?:\+|\.)[a-zA-Z0-9-]+)*)?)$/
  tags:
    - docker
    - docker-nonswiss-ok
    - not-roadrunner
  interruptible: true
  resource_group: integration

build:production:
  image: docker:19.03.11
  stage: "Build"
  services:
    - docker:19.03.11-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    APP_TAG: $CI_COMMIT_REF_NAME
  script:
    - *build
  dependencies:
    - test
  only:
    refs:
      - /^v?\d+\.\d+\.\d+$/
  tags:
    - docker
    - docker-nonswiss-ok
    - not-roadrunner
  interruptible: true
  resource_group: production
