{{- range $variantName, $variant := .Values.deployment.variants -}}
{{- if $variant -}}
apiVersion: {{ template "deployment.apiVersion" $ }}
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "matchd-backend.fullname" $) $variantName }}
  labels:
    app.kubernetes.io/name: {{ template "matchd-backend.name" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ template "matchd-backend.version" $ }}
    app.matchd.ch/environment: {{ template "matchd-backend.environment" $ }}
    helm.sh/chart: {{ template "matchd-backend.chart" $ }}
  annotations:
    backup.velero.io/backup-volumes: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "matchd-backend.name" $ }}
      app.matchd.ch/environment: {{ template "matchd-backend.environment" $ }}
  replicas: {{ $variant.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "matchd-backend.name" $ }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/version: {{ template "matchd-backend.version" $ }}
        app.matchd.ch/environment: {{ template "matchd-backend.environment" $ }}
        helm.sh/chart: {{ template "matchd-backend.chart" $ }}
      annotations:
        backup.velero.io/backup-volumes: media
    spec:
      imagePullSecrets:
      {{- if $.Values.image.secrets }}
{{ toYaml $.Values.image.secrets | indent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RESET_DB
              value: "false"
            - name: SETUP_DB
              value: "false"
            {{- if $.Values.elasticsearch.enabled }}
            - name: ELASTIC_SEARCH_URL
              value: "http://{{ $.Values.elasticsearch.clusterName}}-{{ $.Values.elasticsearch.nodeGroup}}.{{ $.Release.Namespace }}.svc.cluster.local:{{ $.Values.elasticsearch.httpPort}}"
            {{- end }}
            {{- if $.Values.maildev.enabled }}
            - name: SMTP_HOST
              value: "{{ include "matchd-backend.fullname" $ }}-maildev-smtp.{{ $.Release.Namespace }}.svc.cluster.local"
            - name: SMTP_PORT
              value: "{{ $.Values.maildev.services.smtp.port }}"
            - name: SMTP_USE_SSL
              value: 'false'
            - name: SMTP_USE_TLS
              value: 'false'
            - name: SMTP_HOST_PASSWORD
              value: ''
            - name: SMTP_HOST_USER
              value: ''
            {{- end }}
            {{- range $key, $variable := $.Values.env -}}
            {{- if or (and (hasPrefix "ELASTIC_SEARCH_" $key) $.Values.elasticsearch.enabled) (and (hasPrefix "SMTP_" $key) $.Values.maildev.enabled) }}
            #  {{ $key }} has been skipped
            {{- else }}
            {{- $envKey := $key | upper | replace "." "_" | replace "-" "_" }}
            - name: {{ $envKey }}
              value: {{ $variable | toString | replace "str#" "" | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: 8000
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: media
              mountPath: /home/appuser/media
      affinity:
{{- if $variant.nodeAffinity }}
        nodeAffinity:
{{ toYaml $variant.nodeAffinity | indent 10 }}
{{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ template "matchd-backend.name" $ }}
                    - key: app.matchd.ch/environment
                      operator: In
                      values:
                        - {{ template "matchd-backend.environment" $ }}
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "matchd-backend.fullname" $ }}-media
---
{{- end }}
{{- end }}