apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "matchd-backend.fullname" $ }}-media
  labels:
    app.kubernetes.io/name: {{ template "matchd-backend.name" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ template "matchd-backend.version" $ }}
    app.joshmartin.ch/environment: {{ template "matchd-backend.environment" $ }}
    helm.sh/chart: {{ template "matchd-backend.chart" $ }}
  annotations:
    gcs.csi.ofek.dev/bucket: {{ printf "%s-%s-media" $.Release.Namespace (include "matchd-backend.fullname" $) | trunc 63 | trimSuffix "-" }}
    gcs.csi.ofek.dev/uid: "1010"
    gcs.csi.ofek.dev/gid: "1010"
    gcs.csi.ofek.dev/limit-ops-per-sec: "1000"
spec:
  storageClassName: csi-gcs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi