apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "matchd-frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "matchd-frontend.name" .}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ template "matchd-frontend.version" .}}
    app.matchd.ch/environment: {{ template "matchd-frontend.environment" .}}
    helm.sh/chart: {{ template "matchd-frontend.chart" .}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "matchd-frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "matchd-frontend.name" .}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ template "matchd-frontend.version" .}}
    app.matchd.ch/environment: {{ template "matchd-frontend.environment" .}}
    helm.sh/chart: {{ template "matchd-frontend.chart" .}}
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "matchd-frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "matchd-frontend.name" .}}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ template "matchd-frontend.version" .}}
    app.matchd.ch/environment: {{ template "matchd-frontend.environment" .}}
    helm.sh/chart: {{ template "matchd-frontend.chart" .}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "matchd-frontend.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "matchd-frontend.fullname" . }}