apiVersion: v1
description: A Helm chart for deploying a simple site
name: matchd-backend
version: 1.0.0
dependencies:
  - name: elasticsearch
    condition: elasticsearch.enabled
    version: "7.17.3"
    repository: "https://helm.elastic.co"
  - name: maildev
    condition: maildev.enabled
    version: "1.1.1"
    repository: "https://cnieg.github.io/helm-charts"