# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
version:
name:
fullname:
environment:
releaseLabel:
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
deployment:
  secretMounts: []
  variants:
    stable:
      replicaCount: 0
      autoscaling:
        enabled: false
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
    regular:
      replicaCount: 1
      autoscaling:
        enabled: true
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
            weight: 100
ingress:
  enabled: true
  # domain: my.host.com
  monitoring: false
env: {}
elasticsearch:
  enabled: true
  clusterName: "elasticsearch"
  nodeGroup: "master"
  extraEnvs:
  - name: xpack.security.enabled
    value: "false"
  httpPort: 9200
  replicas: 2
  minimumMasterNodes: 1
migrate:
  resetDb: false
maildev:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/acme-http01-edit-in-place: 'false'
      cert-manager.io/cluster-issuer: letsencrypt-production
  services:
    smtp:
      type: ClusterIP
      port: 1025