# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
version:
name:
fullname:
environment:
releaseLabel:
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
deployment:
  annotations: {}
  secretMounts: []
  variants:
    stable:
      replicaCount: 0
      autoscaling:
        enabled: false
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
    regular:
      replicaCount: 1
      autoscaling:
        enabled: true
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
            weight: 100
ingress:
  enabled: true
  hosts: []
    # - host: my.host.com:
    #   port: 80
    #   name: http
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
  letsencrypt: false
  monitoring: false
  tlsSecretName: chart-example-tls
resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi
env: {}
livenessProbe:
  enabled: true
  type: httpGet
  httpGet:
    path: /
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 2
readinessProbe:
  enabled: true
  type: httpGet
  httpGet:
    path: /
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 10
storages: []
  # - name: uploads
  #   enableBackup: false
  #   mountPath: /uploads
  #   pvc:
  #     defaultBucketName: true
  #     size: 25Gi
  #     storageClassName: csi-gcs
  #     annotations:
  #       gcs.csi.ofek.dev/gid: "82" # User: www-data
  #       gcs.csi.ofek.dev/limit-ops-per-sec: "1000" # Rate Limit
elasticsearch:
  enabled: true
  clusterName: "elasticsearch"
  nodeGroup: "master"
  httpPort: 9200
  replicas: 2
  minimumMasterNodes: 1
maildev:
  enabled: true
  services:
    smtp:
      port: 25