on:
  pull_request:
    branches:
      - "*"

name: "Pull Request"

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml@main
  
  build:
    name: "Build"

    uses: ./.github/workflows/part_build.yml@main
  
  dependabot:
    name: "Dependabot"

    needs: ['test', 'build']

    uses: ./.github/workflows/part_dependabot.yml@main